### PR TITLE
Fix keyboard navigation commands

### LINKED ISSUE #71: Keyboard navigation between different files is broken
Keyboard navigation between repr. steps doesn't work outside of the active report's file, so when it would jump into a different file, it doesn't open that file. Same thing when jumping with the cursor in a different file.

### PR DESCRIPTION
**Pull request by Discookie**
Fixes #71.

### CODE REVIEW

**Review by csordasmarton — CHANGES_REQUESTED** [review]
I have the following test files:
**main.h**:
```h
#ifndef MAIN_H
#define MAIN_H

int foo(int param) {
  return param;
}

#endif
```

**main.cpp**:
```cpp
#include "main.h"

int main() {
  return 1 / foo(0);
}
```

If I analyze it CodeChecker will find the following report:
image

Let's assume that I click on the second bug step:
image

Now if I run the Next step command nothing happens:
image

I assumed that your patch fixes this use case so the editor will open main.h and select the correct ranges.

**Comment by Discookie** [comment]
That is a very good example for testing overlapping ranges, thank you!
Fixed it so it prioritizes exact matches over matching the step's range, but it still doesn't quite work in this case.

The issue is that the 2nd (calling foo) and 5th (returning from foo) steps have the exact same location. The extension has no memory of which step it's supposed to be on, so stepping backwards always steps from Calling and forwards from Returning.
Dealing with these exact overlaps is better fit for a separate issue I believe.

**Review by csordasmarton — CHANGES_REQUESTED** [review]
I don't really see what kind of problem this PR solves. Can you please describe the steps what previously don't work but with your patch it will work with a code example?

Also if we don't want to fix the problem fully could you please create another issue for it?

**Review by csordasmarton — APPROVED** [review]
LGTM!

**Pull request merged**
